const assert = require('assert')
const postage = require('../miniprogram/utils/postage')

assert.strictEqual(postage.calculate({ serviceId: 'LETTER', weight: 20, locality: 'LOCAL' }).total, 0.8)
assert.strictEqual(postage.calculate({ serviceId: 'LETTER', weight: 101, locality: 'NON_LOCAL' }).total, 8)
assert.strictEqual(postage.calculate({ serviceId: 'REGISTERED_LETTER', weight: 20, locality: 'LOCAL' }).total, 3.8)
assert.strictEqual(postage.calculate({ serviceId: 'REGISTERED_LETTER', weight: 20, locality: 'LOCAL', appointed: true }).total, 5.8)
assert.strictEqual(postage.calculate({ serviceId: 'POSTCARD' }).total, 0.8)
assert.strictEqual(postage.calculate({ serviceId: 'PRINTED_MATTER', weight: 101, locality: 'NON_LOCAL' }).total, 1.6)
assert.strictEqual(postage.calculate({ serviceId: 'HOMETOWN_PARCEL', weight: 3001 }).total, 11)
assert.strictEqual(postage.calculate({ serviceId: 'ORDINARY_PARCEL', weight: 1500, originId: 'CN-SC', destinationId: 'CN-SC' }).total, 6)
const volumetric = postage.calculate({ serviceId: 'ORDINARY_PARCEL', weight: 1500, length: 60, width: 40, height: 30, originId: 'CN-SC', destinationId: 'CN-SC' })
assert.strictEqual(volumetric.volumetricWeight, 12000)
assert.strictEqual(volumetric.total, 27)
assert.strictEqual(postage.calculate({ serviceId: 'LETTER', weight: 20, locality: 'LOCAL', insured: true, declaredValue: 100 }).total, 4.8)
assert.throws(() => postage.calculate({ serviceId: 'ORDINARY_PARCEL', weight: 1000, originId: 'CN-SH', destinationId: 'CN-SC' }), /暂无普通包裹资费数据/)
assert.strictEqual(postage.inferRegionId('四川省成都市高新区'), 'CN-SC')
console.log('postage calculator tests passed')
